import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Nextjs Admin Dashboard Boilerplate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1 className="text-4xl">Hello World</h1>
      </div>
    </div>
  )
}
